---
name: Sig-PackageScoped
version: 0.04
author:
  - 'Dave Rolsky <autarch@urth.org>'
abstract: 'Make $SIG{__DIE__} and $SIG{__WARN__} package scoped'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  Sig::PackageScoped:
    file: lib/Sig/PackageScoped.pm
    version: 0.04
  Sig::PackageScoped::Paranoid:
    file: lib/Sig/PackageScoped/Paranoid.pm
    version: 99
  Sig::PackageScoped::Paranoid::Tie:
    file: lib/Sig/PackageScoped/Paranoid.pm
    version: 99
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
